/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResumeRouteImport } from './routes/resume'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkPantryAiRouteImport } from './routes/work.pantry-ai'
import { Route as WorkNcrAssistantRouteImport } from './routes/work.ncr-assistant'
import { Route as WorkEventCompassRouteImport } from './routes/work.event-compass'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeRoute = ResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkPantryAiRoute = WorkPantryAiRouteImport.update({
  id: '/work/pantry-ai',
  path: '/work/pantry-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkNcrAssistantRoute = WorkNcrAssistantRouteImport.update({
  id: '/work/ncr-assistant',
  path: '/work/ncr-assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkEventCompassRoute = WorkEventCompassRouteImport.update({
  id: '/work/event-compass',
  path: '/work/event-compass',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/resume': typeof ResumeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/work/event-compass': typeof WorkEventCompassRoute
  '/work/ncr-assistant': typeof WorkNcrAssistantRoute
  '/work/pantry-ai': typeof WorkPantryAiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/resume': typeof ResumeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/work/event-compass': typeof WorkEventCompassRoute
  '/work/ncr-assistant': typeof WorkNcrAssistantRoute
  '/work/pantry-ai': typeof WorkPantryAiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/resume': typeof ResumeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/work/event-compass': typeof WorkEventCompassRoute
  '/work/ncr-assistant': typeof WorkNcrAssistantRoute
  '/work/pantry-ai': typeof WorkPantryAiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/resume'
    | '/sitemap.xml'
    | '/work/event-compass'
    | '/work/ncr-assistant'
    | '/work/pantry-ai'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/resume'
    | '/sitemap.xml'
    | '/work/event-compass'
    | '/work/ncr-assistant'
    | '/work/pantry-ai'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/resume'
    | '/sitemap.xml'
    | '/work/event-compass'
    | '/work/ncr-assistant'
    | '/work/pantry-ai'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ResumeRoute: typeof ResumeRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WorkEventCompassRoute: typeof WorkEventCompassRoute
  WorkNcrAssistantRoute: typeof WorkNcrAssistantRoute
  WorkPantryAiRoute: typeof WorkPantryAiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume': {
      id: '/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof ResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/pantry-ai': {
      id: '/work/pantry-ai'
      path: '/work/pantry-ai'
      fullPath: '/work/pantry-ai'
      preLoaderRoute: typeof WorkPantryAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/ncr-assistant': {
      id: '/work/ncr-assistant'
      path: '/work/ncr-assistant'
      fullPath: '/work/ncr-assistant'
      preLoaderRoute: typeof WorkNcrAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/event-compass': {
      id: '/work/event-compass'
      path: '/work/event-compass'
      fullPath: '/work/event-compass'
      preLoaderRoute: typeof WorkEventCompassRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ResumeRoute: ResumeRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WorkEventCompassRoute: WorkEventCompassRoute,
  WorkNcrAssistantRoute: WorkNcrAssistantRoute,
  WorkPantryAiRoute: WorkPantryAiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
